version: "3"
services:
  famtube-backend:
    container_name: famtube-backend
    image: famtube-backend
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - mongo
  famtube-frontend:
    container_name: famtube-frontend
    image: famtube-frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - famtube-backend
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'