version: "3"
services:
  youtube-search-backend:
    container_name: youtube-search-backend
    image: youtube-search-backend
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - mongo
  youtube-search-frontend:
    container_name: youtube-search-frontend
    image: youtube-search-frontend
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - youtube-search-backend
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'