const SEARCH_FREQUENCY_MINUTES = 10
const MAX_SEARCH_LIMIT = 15
const MAX_RESULTS = 10
const MIN_CONFIDENCE = 10.00

module.exports = {
    SEARCH_FREQUENCY_MINUTES,
    MAX_SEARCH_LIMIT,
    MAX_RESULTS,
    MIN_CONFIDENCE
}