const YOUTUBE_API_KEY = 'AIzaSyBPKHDmEycPw7V6Z43SRsZ4cuaxca1KNoc'
const ALTERNATE_API_KEYS = ['AIzaSyCV5i-LrSJLSwkuZwfKo1j7GSFbrYrDI0A', 'AIzaSyAgQ6MO2CtN7KCBcBnSkh4UMzGOCYKNZJI']

module.exports = {
    YOUTUBE_API_KEY,
    ALTERNATE_API_KEYS
}